print("welcome to the world of programming")
print(4)
print("hello python \n")
print("hello", 5)
print("god is good")
print("god is great")
print("if we pray")
print("he will save")
print("**", end="*")
